server:
  port: 8001
  servlet:
    context-path: /api/v1
spring:
#  config:
#    import: optional:file:.env
#  servlet:
#    multipart:
#      location: ${FILE_LOCATION}
#      enabled: true
#      max-file-size: 1000MB
#      max-request-size: 1000MB
  datasource:
    url: jdbc:postgresql://localhost:5432/coderriders
    username: user
    password: "1234"
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      continue-on-error: true
trace: true